---
version: '3.0'
services:
  busybox:
    image: docker.io/library/busybox@sha256:6e494387c901caf429c1bf77bd92fb82b33a68c0e19f6d1aa6a3ac8d27a7049d
    volumes:
      - /mnt/busybox:/srv/busybox
    command: |
      echo "Hello from busybox at $(date)" >> /srv/busybox/log.txt && cat /srv/busybox/log.txt
    