name: Controller Package

# on:
#   release:
#     types: [created]

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ 'linux' ]
        architecture: [ 'amd64', 's390x', 'arm64' ]
    permissions:
      contents: read
      packages: write
    steps:
      # https://github.com/actions/setup-go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - run: go version
      - run: mkdir -p target

      - name: Test
        run: go test .\...

      - name: Build ${{ matrix.os }}/${{ matrix.architecture }}
        run: CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.architecture }} build -v -ldflags "-X github.com/ibm-hyper-protect/k8s-operator-hpcr/cli.compiled=$(date +%s) -s -w" -o target/${{ matrix.os }}/${{ matrix.architecture }}/k8s-operator-hpcr main.go         
      - run: cp Dockerfile target/${{ matrix.os }}/${{ matrix.architecture }}/Dockerfile

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: target/${{ matrix.os }}/${{ matrix.architecture }}
          push: true
          sbom: true
          tags: ghcr.io/ibm-hyper-protect/k8s-operator-hpcr:latest
